rmdir dist\ /s /q
rmdir build\ /s /q
rmdir py_tgcalls.egg-info\ /s /q
python3.6 setup.py sdist bdist_wheel
rmdir build\ /s /q
python3.7 setup.py sdist bdist_wheel
rmdir build\ /s /q
python3.8 setup.py sdist bdist_wheel
rmdir build\ /s /q
python3.9 setup.py sdist bdist_wheel
rmdir build\ /s /q
rmdir py_tgcalls.egg-info\ /s /q
