[project]
dynamic = ["version"]
name = "py-tgcalls"
description = "Async client API for the Telegram Calls."
readme = "README.md"
license-files = ["LICENSE"]
classifiers = [
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3 :: Only',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
]
authors = [
    {name = "Lauren Iraci", email = "iraci.lauren@gmail.com"},
]
keywords = [
    "audio", "python", "library", "video", "telegram", "stream",
    "ffmpeg", "cpp", "webrtc", "voice-chat", "voip", "group-chat",
    "video-calls", "calls", "video-chat", "pytgcalls", "ntgcalls",
    "tgcalls", "py-tgcalls", "pyrogram", "telethon"
]
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.9.3",
    "ntgcalls>=3.0.0rc2,<4.0.0",
    "deprecation",
]

[project.optional-dependencies]
pyrogram = ["pyrogrammod>=2.1.2"]
telethon = ["telethon>=1.24.0"]

[project.urls]
Homepage = "https://pytgcalls.github.io/"
Repository = "https://github.com/pytgcalls/pytgcalls.git"
Documentation = "https://pytgcalls.github.io/PyTgCalls"
Changelog = "https://pytgcalls.github.io/PyTgCalls/Changelogs"

[tool.setuptools]
include-package-data = true

[tool.ruff]
line-length = 79
target-version = "py310"

[tool.ruff.lint]
select = ["E", "W", "F", "I", "UP"]

[tool.ruff.lint.isort]
force-single-line = true

[tool.ruff.format]
quote-style = "single"

[build-system]
requires = ["setuptools >= 69.2.0", "wheel >= 0.43.0"]

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
]

[tool.setuptools.packages.find]
include = ["pytgcalls*"]
