name: 🚀 Feature Request
description: Suggest a new feature or enhancement for Py-TgCalls.
labels: ['Needs: Triage :mag:', 'type:feature-request']

body:
- type: markdown
  attributes:
    value: |
      # Feature Request

      Thank you for taking the time to suggest a new feature or enhancement for Py-TgCalls!
      
      Please use the sections below to provide detailed information about your suggestion.
      
      - Make sure your idea is clearly explained.
      - Describe the benefits and context for this feature.
      - If you have ideas for implementation, feel free to share them.
      - Check for duplicate requests before submitting.
      
      *Incomplete requests may be automatically closed.*
- type: input
  id: feature-summary
  validations:
    required: true
  attributes:
    label: Feature Summary
    description: Provide a brief summary of the feature or enhancement.
    placeholder: e.g., Add support for X protocol.
- type: textarea
  id: feature-details
  validations:
    required: true
  attributes:
    label: Detailed Description
    description: Describe the feature in detail, including its benefits and how it would be used.
    placeholder: Provide a detailed description of your feature request.
- type: textarea
  id: use-case
  validations:
    required: true
  attributes:
    label: Use Case
    description: Explain the scenario or context in which this feature would be beneficial.
    placeholder: Describe a typical scenario for using this feature.
- type: textarea
  id: additional-info
  attributes:
    label: Additional Information
    description: Add any other context, links, or screenshots that might help us evaluate your feature request.
    placeholder: Provide additional context or resources.